// Generated by CoffeeScript 2.5.1
(function() {
  require('./preload.js');

  l(kup);

  serveIt(kup.render(function() {
    doctype(5);
    return html(function() {
      head(function() {
        meta({
          charset: 'utf-8'
        });
        title(`${this.title || 'Untitled'} | My awesome website`);
        if (this.desc != null) {
          meta({
            name: 'description',
            content: this.desc
          });
        }
        link({
          rel: 'stylesheet',
          href: '/stylesheets/app.css'
        });
        style(`body {font-family: sans-serif}
header, nav, section, footer {display: block}`);
        script({
          src: '/javascripts/jquery.js'
        });
        return coffeescript(function() {
          return $(function() {
            return alert('Alerts are so annoying...');
          });
        });
      });
      body(function() {
        header(function() {
          h1(this.title || 'Untitled');
          return nav(function() {
            return ul(function() {
              var ref;
              if (this.path !== '/') {
                li(function() {
                  return a({
                    href: '/'
                  }, function() {
                    return 'Home';
                  });
                });
              }
              li(function() {
                return a({
                  href: '/chunky'
                }, function() {
                  return 'Bacon!';
                });
              });
              switch ((ref = this.user) != null ? ref.role : void 0) {
                case 'owner':
                case 'admin':
                  return li(function() {
                    return a({
                      href: '/admin'
                    }, function() {
                      return 'Secret Stuff';
                    });
                  });
                case 'vip':
                  return li(function() {
                    return a({
                      href: '/vip'
                    }, function() {
                      return 'Exclusive Stuff';
                    });
                  });
                default:
                  return li(function() {
                    return a({
                      href: '/commoners'
                    }, function() {
                      return 'Just Stuff';
                    });
                  });
              }
            });
          });
        });
        section(function() {
          var i, j, ref, results;
          h2(`Let's count to ${this.max}:`);
          results = [];
          for (i = j = 1, ref = this.max; (1 <= ref ? j <= ref : j >= ref); i = 1 <= ref ? ++j : --j) {
            results.push(p(i));
          }
          return results;
        });
        return footer(function() {
          return p(dumpVar(this));
        });
      });
      return {
        title: 'Foo',
        path: '/zig',
        user: {},
        max: 12,
        locals: {
          shoutify: function(s) {
            return s.toUpperCase() + '!';
          }
        }
      };
    });
  }));

}).call(this);
